---
- name: Deploy Full Stack to Kubernetes
  hosts: local
  connection: local
  gather_facts: no
  
  vars_files:
    - secrets.yaml

  tasks:
    # 1. Apply Manifests (Creating deployments if they don't exist)
    - name: Apply Backend Manifest
      command: kubectl apply -f k8s/backend.yaml

    - name: Apply Frontend Manifest
      command: kubectl apply -f k8s/frontend.yaml

    # 2. Update Images (Using the registry var from Vault + tag from Jenkins)
    - name: Update Backend Image
      command: kubectl set image deployment/backend backend={{ docker_registry }}/oyo-backend:{{ image_tag }}

    - name: Update Frontend Image
      command: kubectl set image deployment/frontend frontend={{ docker_registry }}/oyo-frontend:{{ image_tag }}